spring.application.name=foodieapi

spring.datasource.url=jdbc:mysql://localhost:3306/FoodiesDb
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cloudinary.cloud-name=dfpdztdnx
cloudinary.api-key=154296342646354
cloudinary.api-secret=a6KG6bOUGJpikwyXgfq44DGynFc
jwt.secret.key=a07cdc3c941f1158a0e0ac437c8a507ed05b002c268a900298843b903566260c
