spring.application.name=foodieapi

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernatcde.dialect=org.hibernate.dialect.MySQLDialect

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
jwt.secret.key=${JWT_SECRET_KEY}

razorpay_test_id = ${RAZORPAY_TEST_ID}
razorpay_test_secret = ${RAZORPAY_TEST_SECRET}

frontend.user.url = ${FRONTEND_USER_URL}
frontend.admin.url = ${FRONTEND_ADMIN_URL}

admin.email = ${ADMIN_EMAIL}
admin.password = ${ADMIN_PASSWORD}